version: '3'
services:
  # withdrawal, deposit
  mock-service:
    container_name: mock-service
    build: ./mock_service
    entrypoint: ["./mock-service"]
    volumes:
      - ./pubsub_credentials.json:/kbc-mock-service/pubsub_credentials.json
    environment:
      - GRPC_ADDR=0.0.0.0
    
  # withdrawal, query
  order-grpc:
    image: gcr.io/dabenxiang226/kbc_order:latest
    ports:
      - "7070:7070"
    restart: always
    entrypoint: ["./order", "grpc"]
    volumes:
      - ./configs/order_grpc:/kbc-order/configs
      - ./pubsub_credentials.json:/kbc-order/pubsub_credentials.json
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3309
      - AMS_DATABASE_HOST=host.docker.internal
      - AMS_DATABASE_PORT=3309
      - GRPC_AMS_ADDRESS=mock-service
      - GRPC_AMS_PORT=10050
    depends_on: 
      - db

  # deposit
  order-worker:
    image: gcr.io/dabenxiang226/kbc_order:latest
    ports:
      - "7071:7071"
    restart: always
    entrypoint: ["./order", "worker"]
    volumes:
      - ./configs/order_grpc:/kbc-order/configs
      - ./pubsub_credentials.json:/kbc-order/pubsub_credentials.json
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3309
      - AMS_DATABASE_HOST=host.docker.internal
      - AMS_DATABASE_PORT=3309
      - GRPC_AMS_ADDRESS=ams-grpc
      - GRPC_AMS_PORT=10050
    depends_on: 
      - db

  # deposit wallet
  ams-grpc:
    container_name: ams-grpc
    image: gcr.io/dabenxiang226/kbc_ams:latest
    # image: gcr.io/silkrode-golang/kbc-ams:latest
    ports:
      - "10050:10050"
    restart: always
    entrypoint: ["./kbc-ams", "grpc"]
    volumes:
      - ./configs/ams_grpc:/kbc-ams/configs
      - ./pubsub_credentials.json:/kbc-ams/pubsub_credentials.json
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=3309
    depends_on: 
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=kbc
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3309:3306"
    volumes:
      - kbc_db:/var/lib/mysql

volumes:
  kbc_db:
